using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Bird : MonoBehaviour
{
    private bool isDead = false;
    private Rigidbody2D rb2d;
    public float upForce =200f;
  

    private void Awake()
    {
        
        rb2d = GetComponent<Rigidbody2D>();
    }
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        if (isDead) return;
        
            if (Input.GetMouseButtonDown(0)) 
            {
                rb2d.velocity = Vector2.zero;
                rb2d.AddForce(Vector2.up * upForce);
            }
        
    }

    private void OnCollisionEnter2D(Collision2D collision)
    {
        isDead = true;
        GameController.instanceGameController.PlayerDie();
        rb2d.velocity = Vector2.zero;
       
    }
}
